sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t edoparearyee/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true edoparearyee/react-test npm test

after_success:
  - docker build -t edoparearyee/multi-client ./client
  - docker build -t edoparearyee/multi-nginx ./nginx
  - docker build -t edoparearyee/multi-server ./server
  - docker build -t edoparearyee/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push edoparearyee/multi-client
  - docker push edoparearyee/multi-nginx
  - docker push edoparearyee/multi-server
  - docker push edoparearyee/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-457385982195"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
